Update Mantıksal Bağlaçlar.ipynb
mustafamuratcoskun/Sifirdan-Ileri-Seviyeye-Python-Programlama pull request #16
Opened 2020-09-06 00:35 UTC by ulerdogan

2020-09-06 00:52 UTC, ymucahit commented
Simple typo. Instead of "Çocuk", "Çoçuk" is written. Better to accept the pr.

2020-09-06 00:52 UTC, ymucahit approved these changes

2021-11-06 19:08 UTC, fifitie requested changes
- [ tansel]

2022-11-14 15:12 UTC, cetintas083 commented
Cocuk

2023-10-07 13:00 UTC, closed without merging